#!/bin/sh

while true; do
    if ! pidof mpd > /dev/null; then
        sleepid 3m $1
    else
        echo "M$(mpc current -f "[%artist% - ][%title%|%file%]")"
        mpc idle > /dev/null
    fi
done
