#!/bin/bash

source ~/.zshrc_secrets

appID=$TRIMET_API_APPID
locIDs=$TRIMET_API_LOCID
prefix=m

read -r -d '' filter <<'EOF'
def wholeminutes: . / (1000 * 60) | floor;

.resultSet.arrival
    | .[:2]
    | map((.estimated // .scheduled) - ($now | tonumber) | wholeminutes)
    | $prefix + join("/")
EOF

while true; do
    now=$(date +%s%3N)
    curl -s "http://developer.trimet.org/ws/v2/arrivals?appID=${appID}&locIDs=${locIDs}" \
        | jq -r "${filter}" --arg now "${now}" --arg prefix "${prefix}"
    sleepid 30 $1
done
