#!/bin/bash
DOCUMENTS="$HOME/Documents"
DOTFILES="$DOCUMENTS/Dotfiles"
ARCHIVE="/mnt/archive"

mkdir -p $HOME/.ssh
mkdir -p $HOME/.virtualenvs

ln -sT $ARCHIVE/audio $HOME/Audio
ln -sT $DOTFILES/.bin $HOME/.bin
ln -sT $DOTFILES/.config/user-dirs.dirs $HOME/.config/user-dirs.dirs
ln -sT $DOTFILES/.config/colorschemes $HOME/.config/colorschemes
ln -sT $DOTFILES/.config/bspwm $HOME/.config/bspwm
ln -sT $DOTFILES/.config/sxhkd $HOME/.config/sxhkd
ln -sT $DOTFILES/.config/compton.conf $HOME/.config/compton.conf
ln -sT $DOTFILES/.config/mpd/mpd.conf $HOME/.config/mpd/mpd.conf
ln -sT $DOTFILES/.config/clight.yaml $HOME/.config/clight.yaml
ln -sT $DOTFILES/.gitignore_global $HOME/.gitignore_global
ln -sT $DOTFILES/.password-store $HOME/.password-store
ln -sT $DOTFILES/.ssh/config $HOME/.ssh/config
ln -sT $DOTFILES/.tmux.conf $HOME/.tmux.conf
ln -sT $DOTFILES/.vim $HOME/.vim
ln -sT $DOTFILES/.vimrc $HOME/.vimrc
ln -sT $DOTFILES/.vim $HOME/.config/nvim
ln -sT $DOTFILES/.vimrc $HOME/.config/nvim/init.vim
ln -sT $DOTFILES/.XCompose $HOME/.XCompose
ln -sT $DOTFILES/.Xresources $HOME/.Xresources
ln -sT $DOTFILES/.xinitrc $HOME/.xinitrc
ln -sT $DOTFILES/.zshrc $HOME/.zshrc
ln -sT $DOCUMENTS/Notes/TODO $HOME/TODO
