#!/bin/bash
DOCUMENTS="$HOME/Documents"
DOTFILES="$DOCUMENTS/Dotfiles"
ARCHIVE="/mnt/archive"

mkdir -p $HOME/.ssh
mkdir -p $HOME/.virtualenvs

ln -s $ARCHIVE/audio $HOME/Audio
ln -s $DOTFILES/.bin $HOME/.bin
ln -s $DOTFILES/.config/user-dirs.dirs $HOME/.config/user-dirs.dirs
ln -s $DOTFILES/.config/colorschemes $HOME/.config/colorschemes
ln -s $DOTFILES/.config/herbstluftwm $HOME/.config/herbstluftwm
ln -s $DOTFILES/.config/bspwm $HOME/.config/bspwm
ln -s $DOTFILES/.config/sxhkd $HOME/.config/sxhkd
ln -s $DOTFILES/.config/compton.conf $HOME/.config/compton.conf
ln -s $DOTFILES/.config/mpd/mpd.conf $HOME/.config/mpd/mpd.conf
ln -s $DOTFILES/.fonts $HOME/.fonts
ln -s $DOTFILES/.gitignore_global $HOME/.gitignore_global
ln -s $DOTFILES/.password-store $HOME/.password-store
ln -s $DOTFILES/.ssh/config $HOME/.ssh/config
ln -s $DOTFILES/.tmux.conf $HOME/.tmux.conf
ln -s $DOTFILES/.vim $HOME/.vim
ln -s $DOTFILES/.vimrc $HOME/.vimrc
ln -s $DOTFILES/.XCompose $HOME/.XCompose
ln -s $DOTFILES/.Xresources $HOME/.Xresources
ln -s $DOTFILES/.xinitrc $HOME/.xinitrc
ln -s $DOTFILES/.zshrc $HOME/.zshrc
ln -s $DOCUMENTS/Notes/TODO $HOME/TODO
