#!/bin/bash

xprop -root -f _NET_DESKTOP_LAYOUT 32cccc -set _NET_DESKTOP_LAYOUT 0,0,2,0
xprop -root -f _NET_NUMBER_OF_DESKTOPS 32c -set _NET_NUMBER_OF_DESKTOPS 4

xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/commands/custom/<Control><Alt>n" --set "/home/vreon/.bin/dmenu_custom"

xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/commands/custom/<Control>space" --set "urxvt -name urxvtbig2"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/commands/custom/<Control><Shift>space" --set "urxvt -name urxthuge2"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/commands/custom/<Control><Alt>space" --set "urxvt"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/commands/custom/<Control><Super>space" --set "urxvt -name urxvtlight -borderLess"

xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Alt>m" --set "maximize_window_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Alt>f" --set "fullscreen_key"

xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Alt>h" --set "left_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Alt>j" --set "down_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Alt>k" --set "up_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Alt>l" --set "right_workspace_key"

xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Shift><Alt>h" --set "move_window_left_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Shift><Alt>j" --set "move_window_down_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Shift><Alt>k" --set "move_window_up_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -t string -p "/xfwm4/custom/<Control><Shift><Alt>l" --set "move_window_right_workspace_key"

# TODO: Generate a theme for host_color
# TODO: Generate a background for host_color
