#!/bin/bash
wid=$1
class=$2
instance=$3

get_xprop(){
    local val=$(xprop -id $1 $2)

    if [[ $val == *"not found"* ]]; then
        val='n/a'
    else
        val=$(echo $val | sed 's/.*"\(.*\)".*/\1/')
    fi

    echo -n $val
}

title=$(get_xprop $wid WM_NAME)
role=$(get_xprop $wid WM_WINDOW_ROLE)

case "$title" in
    popterm) echo "state=floating" ;;
esac

case "$role" in
    pop-up) echo "state=floating" ;;
esac
