#!/bin/bash

source ~/.zshrc_secrets

export PASSPHRASE=$DUPLICITY_PASSPHRASE
export AWS_ACCESS_KEY_ID=$DUPLICITY_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$DUPLICITY_AWS_SECRET_ACCESS_KEY

BACKEND="s3://s3-us-west-2.amazonaws.com/chenjesu.backup"

duplicity --full-if-older-than 30D /home/vreon/Documents $BACKEND/home/documents
duplicity --full-if-older-than 30D /home/vreon/Projects $BACKEND/home/projects
duplicity --full-if-older-than 30D /home/vreon/Work $BACKEND/home/work
duplicity --full-if-older-than 30D /mnt/archive/audio $BACKEND/archive/audio
duplicity --full-if-older-than 30D /mnt/archive/video/mine $BACKEND/archive/video/mine
duplicity --full-if-older-than 30D /mnt/archive/photo $BACKEND/archive/photo

duplicity remove-older-than 4M --force $BACKEND/home/documents
duplicity remove-older-than 4M --force $BACKEND/home/projects
duplicity remove-older-than 4M --force $BACKEND/home/work
duplicity remove-older-than 4M --force $BACKEND/archive/audio
duplicity remove-older-than 4M --force $BACKEND/archive/video/mine
duplicity remove-older-than 4M --force $BACKEND/archive/photo
