#!/bin/bash
# Get an overview of the cluster

red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
blue='\e[0;34m'
purple='\e[0;35m'
cyan='\e[0;36m'
white='\e[0;37m'
reset='\e[0m'

section() {
    echo -ne $2
    echo "===== $1 ====="
    kubectl get ${@:3} $1 2>&1
    echo -e $reset
}

nsflags=''
if [[ $1 == '--all' ]]; then
    nsflags='--all-namespaces'
fi

section pods $cyan $nsflags
section deployments $red $nsflags
section replicasets $purple $nsflags
section services $yellow $nsflags
section endpoints $green $nsflags
section secrets $yellow $nsflags
section configmaps $blue $nsflags
section persistentvolumeclaims $purple $nsflags
section resourcequotas $purple $nsflags

# non-namespaced stuff
if [[ $1 == '--all' ]]; then
    section persistentvolumes $cyan
    section namespaces $green
    section nodes $white
fi
