#!/bin/bash
# List all config contexts or set the current context

current=$(kubectl config current-context)

if [[ -z $@ ]]; then
    (
        echo 'NAME#CLUSTER#USER#NAMESPACE'
        kubectl config view -o json | jq -r '.contexts[] | [.name, .context.cluster, .context.user, .context.namespace] | join("#")'
    ) | column -s '#' -t | grep --color=always -E "^${current}.*|$"
else
    kubectl config use-context $@
fi
