#!/bin/bash
# List all contexts or set the current namespace

current=$(kubectl config current-context)

if [[ -z $@ ]]; then
    (
        echo 'NAME#CLUSTER#USER#NAMESPACE'
        kubectl config view -o json | jq -r '.contexts[] | [.name, .context.cluster, .context.user, .context.namespace] | join("#")'
    ) | column -s '#' -t | grep --color=always -E "^${current}\s.*|$"
else
    kubectl config set-context $current --namespace=$@
    echo "switched to namespace \"$@\"."
fi
