#!/bin/bash
# Get an overview of the cluster

red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
blue='\e[0;34m'
purple='\e[0;35m'
cyan='\e[0;36m'
white='\e[0;37m'
reset='\e[0m'

section() {
    out=$(kubectl get ${@:3} $1 2>&1)
    if [[ -n $out ]]; then
        echo -ne $2
        echo "===== $1 ====="
        echo "$out"
        echo -e $reset
    fi
}

nsflags=''
if [[ $1 == '--all' ]]; then
    nsflags='--all-namespaces'
fi

# v1 top-level API objects
section configmaps $red $nsflags
section endpoints $green $nsflags
section limitranges $yellow $nsflags
section persistentvolumeclaims $blue $nsflags
section pods $purple $nsflags
section replicationcontrollers $cyan $nsflags
section resourcequotas $white $nsflags
section secrets $red $nsflags
section serviceaccounts $green $nsflags
section services $yellow $nsflags

# v1beta1 top-level API objects
section daemonsets $blue $nsflags
section deployments $purple $nsflags
section horizontalpodautoscalers $cyan $nsflags
section ingresses $white $nsflags
section jobs $red $nsflags
section replicasets $green $nsflags

# non-namespaced stuff
if [[ $1 == '--all' ]]; then
    section namespaces $yellow
    section nodes $blue
    section persistentvolumes $purple
fi
