#!/bin/bash
# Steal a secret from another namespace

SECRET_NAME=$1
OTHER_NAMESPACE=${2:-default}

kubectl get --namespace=${OTHER_NAMESPACE} secret/${SECRET_NAME} -o yaml | \
   sed '/creationTimestamp\|resourceVersion\|selfLink\|uid\|namespace/d' | \
   kubectl apply -f -

kubectl get secret/${SECRET_NAME}
