#!/bin/bash
# Hacky extension framework for kubectl

prefix='kube-'
cmd=$1
shift

if [[ -z "$cmd" ]]; then
    kubectl
    echo
    echo "$(basename $0) extras:"
    compgen -c | grep -e "^${prefix}\\w\\+$" | sort | uniq | while read cmd; do
        echo -n $cmd | sed "s/${prefix}/  /"
        sed -n 2p < $(which $cmd)
    done | column -ts '#' -o ' '
    exit 0
fi

if command -v "${prefix}${cmd}" >/dev/null 2>&1; then
    "${prefix}${cmd}" $@
else
    kubectl $cmd $@
fi
