#!/usr/bin/env python
# Yanks notes out of my todo file for Discogs standup

from __future__ import print_function
import os


def parse_tasks(file_):
    in_today = False

    yesterday = []
    today = []
    blockers = []

    for line in file_.readlines():
        line = line.rstrip()

        if line == 'today':
            in_today = True
            continue

        if not in_today:
            continue

        line = line.strip()

        if not line:
            in_today = False
            continue

        task = line[2:]

        if line.startswith('x'):
            yesterday.append(task)
        elif line.startswith('>'):
            yesterday.append('started: %s' % task)
            today.append('continuing: %s' % task)
        elif line.startswith('-'):
            today.append(task)
        elif line.startswith('<'):
            blockers.append(task)

    return yesterday, today, blockers


def print_tasks(header, tasks, empty_text=None):
    if not tasks and empty_text is not None:
        print(empty_text)
        print()
    elif tasks:
        print('*%s*' % header)
        for task in tasks:
            print('  %s' % task)
        print()


def print_today(todo_filename):
    with open(os.path.expanduser(todo_filename)) as f:
        yesterday, today, blockers = parse_tasks(f)

    print_tasks('Yesterday', yesterday)
    print_tasks('Today', today)
    print_tasks('Blockers', blockers)


if __name__ == '__main__':
    print_today('~/TODO')
