#!/bin/bash
# Use a random saved wallpaper

. splash_config

SELECTED="$DIR/$(ls "$DIR" | grep -v -e "orig" -e "current" | shuf -n 1)"

cp "$SELECTED" "$ORIG"
duotone "$ORIG" "$(xcolor "$(hostcolor)")" > "$CURRENT" && \
    splash_set

echo "$SELECTED"
