#!/bin/sh

# Location of config directory for splash
readonly DIR="$HOME/.config/wallpaper"

# Location of storage for wallpapers
readonly STORE="$DIR/store"

# The currently selected wallpaper, without effects
readonly ORIG="$DIR/orig"

# The currently selected wallpaper, with effects
readonly CURRENT="$DIR/current"

function apply() {
    feh --bg-fill "$CURRENT"
}

function store(){
    local md5=($(md5sum "$1"))
    local saved="$STORE/$md5"
    cp "$1" "$saved"
    exit 0
}

function save() {
    store "$ORIG"
    exit 0
}

function sync() {
    local host=$1

    if [ -z "$host" ]; then
        >&2 echo 'error: sync with which host?'
        exit 1
    fi

    rsync -azhu --progress "${STORE}/" "${host}:${STORE}/"
    rsync -azhu --progress "${host}:${STORE}/" "${STORE}/"

    exit 0
}

function pick() {
    local selected=($(sxiv -N popimage -rtbo "$STORE"))

    [ -n "$selected" ] || exit 0

    rm "$ORIG"
    cp "$selected" "$ORIG"
    rm "$CURRENT"
    cp "$ORIG" "$CURRENT"
    apply
    exit 0
}

function saved() {
    local selected="$STORE/$(ls "$STORE" | grep -v -e "0000000" | shuf -n 1)"
    rm "$ORIG"
    cp "$selected" "$ORIG"
    rm "$CURRENT"
    cp "$ORIG" "$CURRENT"
    apply
    exit 0
}

function web() {
    local url=$(curl -s "http://www.splashbase.co/api/v1/images/random?images_only=true" | jq -r ". | .large_url // .url")
    curl -so "$ORIG" "$url"
    rm "$CURRENT"
    cp "$ORIG" "$CURRENT"
    apply
    exit 0
}

function effect_reset() {
    cp "$ORIG" "$CURRENT"
    apply
}

function effect_duotone() {
    mogrify -colorspace gray +sigmoidal-contrast 3,20% -fill "$(xrq colorscheme.color$(hostcolor))" -tint 50 "$CURRENT"
    apply
}

function effect_lighten() {
    mogrify -fill white -colorize 50% "$CURRENT"
    apply
}

function effect_posterize() {
    local threshold="$1"
    threshold=${threshold:=50%}
    mogrify -threshold "$threshold" -level -50% "$CURRENT"
    apply
}

function effect() {
    while true; do
        local effect=$1
        shift

        if [[ -z "$effect" ]]; then
            break
        fi

        case "$effect" in
            duotone) effect_duotone "$@" ;;
            posterize) effect_posterize "$@" ;;
            lighten) effect_lighten "$@" ;;
            reset) effect_reset "$@" ;;
            *) >&2 echo "Invalid effect: $effect"; exit 1 ;;
        esac
    done

    exit 0
}

function invalid() {
    echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
}

function usage() {
    echo "Usage: $(basename "$0") [-h] COMMAND"
    echo "Manage wallpaper."
    echo
    echo "Commands:"
    echo "  save    Save the current wallpaper"
    echo "  store   Add the named wallpaper to storage"
    echo "  sync    Synchronize wallpaper storage with another host's storage"
    echo "  pick    Interactively pick a wallpaper"
    echo "  web     Select a wallpaper at random from the web"
    echo "  saved   Select a wallpaper at random from saved wallpapers"
    echo "  effect  Interactively pick an effect to apply to the current wallpaper"
    echo
    echo "Options: "
    echo "  -h      Show this usage message and exit"
}


function main() {
    while getopts ":h" opt; do
        case "$opt" in
            h) usage && exit 0 ;;
            \?) invalid ;;
        esac
    done

    shift $((OPTIND -1))

    cmd=$1
    shift

    case "$cmd" in
        save) save ;;
        store) store "$@" ;;
        sync) sync "$@" ;;
        pick) pick ;;
        web) web ;;
        saved) saved ;;
        effect) effect "$@" ;;
        \?) invalid ;;
    esac

    usage >&2
}

main "$@"
