#!/bin/bash
# Prints the hex code for a color from .Xresources

colors=($(xrdb -query | sort -n -t 'r' -k2 | awk '/^.*[\.\*]color/{print $2}'))

if [ -z "$1" ]; then
    echo "${colors[*]}"
else
    echo "${colors[$1]}"
fi
