#!/bin/sh

PANEL_HOME=$HOME/.config/bspwm/panel
PANEL_FIFO=$PANEL_HOME/fifo
PANEL_HEIGHT=20

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf "T%s" > "$PANEL_FIFO" &
clock -sf "S%a %b %-d %-I:%M%P" > "$PANEL_FIFO" &
$PANEL_HOME/scripts/updates > "$PANEL_FIFO" &
$PANEL_HOME/scripts/disk > "$PANEL_FIFO" &
$PANEL_HOME/scripts/playing > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | $PANEL_HOME/dzen.py | dzen2 -ta l -w 1920 -h 20 -dock -fg "#d0d0d0" -bg "#101010" -fn "Fantasque Sans Mono-12px" &

wait
