#!/bin/sh

PANEL_HOME=$HOME/.config/bspwm/panel
PANEL_FIFO=$PANEL_HOME/fifo
PANEL_SLEEPERS=$PANEL_HOME/sleepers
PANEL_HEIGHT=20

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config top_padding $PANEL_HEIGHT

bspc subscribe > "$PANEL_FIFO" &
xtitle -sf "T%s" > "$PANEL_FIFO" &
clock -sf "S%Y-%m-%d %-I:%M%P" > "$PANEL_FIFO" &

for widget in updates disk playing vpn cpu_temp gpu_temp transit; do
    $PANEL_HOME/scripts/$widget $PANEL_SLEEPERS/$widget.pid > "$PANEL_FIFO" &
done

cat "$PANEL_FIFO" | $PANEL_HOME/dzen.py -a "${HOSTCOLOR}" -c "$(xrq -1 colorscheme.color{0..15})" | dzen2 -ta l -w 1920 -h 20 -dock -fg "$(xrq colorscheme.foreground)" -bg "$(xrq colorscheme.color0)" -fn "PragmataPro-11px" -e "" &

wait
