#!/bin/bash

colors=($(xrq -1 colorscheme.color{0..15}))
primary=$(hostcolor)

bspc config border_width        2
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config auto_cancel         true
bspc config initial_polarity    second_child

bspc config normal_border_color "${colors[0]}"
bspc config focused_border_color "${colors[$primary]}"
bspc config presel_border_color \#ffffff
bspc config normal_private_border_color "${colors[8]}"
bspc config focused_private_border_color "${colors[7]}"
bspc config urgent_border_color "${colors[9]}"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config external_rules_command $HOME/.bin/bspwm-rules

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd floating=on  # hangouts
bspc rule -a Thunar floating=on
bspc rule -a popimage floating=on

$HOME/.config/bspwm/panel/panel &
